name: Antithesis Integration

on:
  push:

env: 
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0

    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      run: earthly --push +build-all

    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: formance__configuration-internal__latest
        tenant: formance
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}
        images: antithesis-config:latest;workload:latest;ledger:latest
