name: Antithesis Integration

on:
  push:

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0

    - uses: actions/checkout@v4

    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

    - name: Build and Push
      run: earthly --push +build-all

    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: formance__configuration-internal__latest
        tenant: formance
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}
        images: antithesis-config:latest;workload:latest;ledger:latest
